---

- name: linux - launch a compute instance
  openstack.cloud.server:
    state: present
    name: "{{ item.name }}"
    image: "{{ item.image | default(omit) }}"
    key_name: "{{ item.key_name }}"
    timeout: "{{ instance_timeout }}"
    flavor: "{{ item.flavor }}"
    nics: "{{ item.nics }}"
    boot_from_volume: "{{ _boot_from_volume }}"
    terminate_volume: "{{ _terminate_volume }}"
    boot_volume: "{{ _boot_volume }}"
    volume_size: "{{ item.volume_size }}"
    userdata: "{{ item.user_data | default('') }}"
    meta:
      hostname: "{{ item.name }}"
      role: "{{ item.role }}"
      app_name: "{{ item.app_name }}"
    auto_ip: "{{ omit if (floating_ips | length) else (item.auto_ip | default ('yes')) }}"
    floating_ips: "{{ floating_ips if (floating_ips | length) else omit }}"
    volumes: "{{ server_volumes }}"
    wait: yes
    validate_certs: "{{ openstack_validate_certs }}"
  register: deploy_linux
  loop: "{{ nodes }}"
  when:
    - nodes is defined
    - item.os_type is not defined or (item.os_type is defined and item.os_type | lower == 'linux')

- name: windows - launch a compute instance
  openstack.cloud.server:
    state: present
    name: "{{ item.name }}"
    image: "{{ item.image | default(omit) }}"
    key_name: "{{ item.key_name }}"
    timeout: "{{ instance_timeout }}"
    flavor: "{{ item.flavor }}"
    nics: "{{ item.nics }}"
    boot_from_volume: "{{ _boot_from_volume }}"
    terminate_volume: "{{ _terminate_volume }}"
    boot_volume: "{{ _boot_volume }}"
    volume_size: "{{ item.volume_size }}"
    userdata: "{{ item.user_data | default(lookup('template', 'templates/userdata.txt.j2')) }}"
    meta:
      hostname: "{{ item.name }}"
      role: "{{ item.role }}"
      app_name: "{{ item.app_name }}"
    auto_ip: "{{ omit if (floating_ips | length) else (item.auto_ip | default ('yes')) }}"
    floating_ips: "{{ floating_ips if (floating_ips | length) else omit }}"
    volumes: "{{ server_volumes }}"
    wait: yes
    validate_certs: "{{ openstack_validate_certs }}"
  register: deploy_windows
  loop: "{{ nodes }}"
  when:
    - nodes is defined
    - item.os_type is defined
    - item.os_type | lower == 'windows'

- name: combine deployment results
  set_fact:
    deploy_results: "{{ deploy_results|default([]) + [ item ] }}"
  loop: "{{ deploy_linux.results + deploy_windows.results }}"
  no_log: yes
  when:
    - nodes is defined
    - (item.skipped is not defined) or not item.skipped

- name: set instances results
  set_fact:
    instances: "{{ {'results': deploy_results } }}"